
- name: Set Document Viewer as the default PDF application
  command: xdg-mime default org.gnome.Evince.desktop application/pdf
  args:
    removes: "/usr/share/applications/evince.desktop"
- name: Update apt package index
  apt:
    update_cache: yes
  become: true
- name: Install Synaptics DisplayPort driver
  apt:
    name: xserver-xorg-input-synaptics
    state: present
  become: true